Repository X-R-G-B/koaky, pull requests merged in 2023-12, with the labels that each got.

#8 2 parse text to ast
  .github/workflows/tests.yml
  .gitignore
  app/Main.hs
  src/AST.hs
  src/TextToAST.hs
  test/Spec.hs
Labels: enhancement

#14 13 compute with new tree type
  app/Main.hs
  koaky.cabal
  src/AST.hs
  src/ComputeAST.hs
  src/ComputeDeepLists.hs
  src/ComputeLists.hs
  src/Defines.hs
  src/Errors.hs
  src/Functions.hs
  src/Types.hs
  test/Spec.hs
Labels: enhancement, TEST

#15 Parser v2
  .gitignore
  koaky.cabal
  src/Parser.hs
  src/TextToAST.hs
  test/Spec.hs
Labels: enhancement

#17 Dev
  .github/workflows/documentation.yml
  .github/workflows/tests.yml
  .gitignore
  Makefile
  app/Main.hs
  docs/Coverage.md
  docs/SUMMARY.md
  koaky.cabal
  src/AST.hs
  src/ComputeAST.hs
  src/Computing/ComputeAST.hs
  src/Computing/ComputeDeepLists.hs
  src/Computing/ComputeLists.hs
  src/Computing/Defines.hs
  src/Computing/Errors.hs
  src/Computing/Functions.hs
  src/Parsing/Parser.hs
  src/TextToAST.hs
  src/Types.hs
  test/Spec.hs
Labels: bug, enhancement

#20 19 option help
  app/Args.hs
  app/Main.hs
  app/Run.hs
  app/Version.hs
  koaky.cabal
  src/KoakyLibVersion.hs
Labels: enhancement

#24 Add multiple line handler
  app/Run.hs
Labels: enhancement

#21 Conditions + Result = Either Tree Void
  app/Run.hs
  koaky.cabal
  src/Computing/ComputeAST.hs
  src/Computing/ComputeDeepLists.hs
  src/Computing/ComputeLists.hs
  src/Computing/Defines.hs
  src/Computing/Errors.hs
  src/Computing/Functions.hs
  src/Computing/ListContainList.hs
  src/Computing/Operators/Assert.hs
  src/Computing/Operators/Calculate.hs
  src/Computing/Operators/EvaluateSymbol.hs
  src/Computing/ReplaceFunctionParams.hs
  src/Types.hs
  test/Spec.hs
Labels: enhancement, TEST

#25 Dev to main
  app/Args.hs
  app/Main.hs
  app/Run.hs
  app/Version.hs
  koaky.cabal
  src/Computing/ComputeAST.hs
  src/Computing/ComputeDeepLists.hs
  src/Computing/ComputeLists.hs
  src/Computing/Defines.hs
  src/Computing/Errors.hs
  src/Computing/Functions.hs
  src/Computing/ListContainList.hs
  src/Computing/Operators/Assert.hs
  src/Computing/Operators/Calculate.hs
  src/Computing/Operators/EvaluateSymbol.hs
  src/Computing/ReplaceFunctionParams.hs
  src/KoakyLibVersion.hs
  src/Types.hs
  test/Spec.hs
Labels: documentation, enhancement, TEST

#27 enhance display for users
  src/Types.hs
Labels: enhancement
